<a href="https://colab.research.google.com/github/Ishan-1104/ML-1/blob/main/Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix Addition

In [2]:
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
sum = A+B

In [6]:
print(sum)

[[ 8 10]
 [12 14]]


In [7]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [8]:
print(matrix_1)

[[1 3 0]
 [5 2 1]
 [1 0 4]]


In [9]:
print(matrix_2)

[[ 7 18 19]
 [14 19  8]
 [10 18  7]]


In [10]:
matrix_1.shape

(3, 3)

In [11]:
matrix_2.shape

(3, 3)

In [12]:
sum2 = matrix_1 + matrix_2

In [13]:
print(sum2)

[[ 8 21 19]
 [19 21  9]
 [11 18 11]]


Matrix **Subtraction**

In [14]:
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [15]:
diff = A-B

In [16]:
print(diff)

[[-4 -4]
 [-4 -4]]


In [17]:
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [18]:
print(matrix_1)

[[2 6 3]
 [5 3 2]
 [0 6 5]]


In [19]:
print(matrix_2)

[[ 2 12  0]
 [13  7 18]
 [ 6  5 18]]


In [22]:
diff2 = np.subtract(matrix_1, matrix_2)

In [23]:
print(diff2)

[[  0  -6   3]
 [ -8  -4 -16]
 [ -6   1 -13]]


Multiplying a matrix by a scalar

In [24]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[3 9 5 3]
 [7 2 5 0]
 [3 9 2 5]
 [8 1 3 3]]


In [25]:

product = np.multiply(x,y)

In [26]:
print(product)

[[15 45 25 15]
 [35 10 25  0]
 [15 45 10 25]
 [40  5 15 15]]


Multiplying 2 Matrices

In [27]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [28]:
print(matrix_3)

[[4 0 2]
 [3 4 4]
 [3 4 1]]


In [29]:
print(matrix_4)

[[0 3 4 2]
 [4 3 3 2]
 [3 3 2 2]]


In [30]:
product = np.dot(matrix_3, matrix_4)

In [31]:
print(product)

[[ 6 18 20 12]
 [28 33 32 22]
 [19 24 26 16]]
